spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/persondb
    username: person
    password: person

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true