server:
  port: 8081
spring:

  flyway:
    locations: classpath:db/migration
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5437/persondb
    username: person
    password: person

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  